apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ovd7ibn0x-nodejs
  janus-idp.io/tekton: ovd7ibn0x-nodejs
  backstage.io/kubernetes-id: ovd7ibn0x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ovd7ibn0x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
